# Generated by Django 2.1.7 on 2019-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('train', models.CharField(max_length=32)),
                ('result', models.CharField(max_length=256)),
            ],
        ),
    ]
